/**
 * Ikony liniowe do kart produktów — generowane w Higgsfield (gpt_image_2),
 * cięte z arkuszy, kreska pogrubiona morfologią, żeby były czytelne w 24–32 px.
 * Na jasnym tle używane z klasą `mix-blend-multiply`.
 *
 * ZASADA: jedna ikona = jedna cecha. Nie podpinać tej samej ikony pod różne
 * twierdzenia (np. jasność ekranu i jego przekątna to osobne ikony).
 */
export const ICON = {
  // ekran
  jasnosc: '/icons/line/jasnosc.png',
  przekatna: '/icons/line/przekatna.png',
  plynnosc: '/icons/line/plynnosc.png',
  rozdzielczosc: '/icons/line/rozdzielczosc.png',
  jednareka: '/icons/line/jednareka.png',
  // zasilanie
  czaspracy: '/icons/line/czaspracy.png',
  wymiana: '/icons/line/wymiana.png',
  ladowanie: '/icons/line/ladowanie.png',
  dok: '/icons/line/dok.png',
  bateria: '/icons/em45/line/bateria.png',
  // odporność
  woda: '/icons/em45/line/woda.png',
  upadek: '/icons/em45/line/upadek.png',
  mroz: '/icons/line/mroz.png',
  norma: '/icons/line/norma.png',
  szklo: '/icons/line/szklo.png',
  // funkcje
  skaner: '/icons/line/skaner.png',
  lidar: '/icons/line/lidar.png',
  aparat: '/icons/line/aparat.png',
  rysik: '/icons/line/rysik.png',
  rekawica: '/icons/line/rekawica.png',
  klawiatura: '/icons/line/klawiatura.png',
  procesor: '/icons/line/procesor.png',
  pamiec: '/icons/line/pamiec.png',
  siec: '/icons/line/siec.png',
  porty: '/icons/line/porty.png',
  smartcard: '/icons/line/smartcard.png',
  odcisk: '/icons/line/odcisk.png',
  ai: '/icons/line/ai.png',
  linux: '/icons/line/linux.png',
  waga: '/icons/line/waga.png',
  antyodblask: '/icons/line/antyodblask.png',
  // druk i dokumenty
  szybkosc: '/icons/line/szybkosc.png',
  kolor: '/icons/line/kolor.png',
  dwustronny: '/icons/line/dwustronny.png',
  adf: '/icons/line/adf.png',
  skandok: '/icons/line/skandok.png',
  nfc: '/icons/line/nfc.png',
  papier: '/icons/line/papier.png',
  kompakt: '/icons/line/kompakt.png',
  // monitory
  usbc: '/icons/line/usbc.png',
  lan: '/icons/line/lan.png',
  kamera: '/icons/line/kamera.png',
  glosnik: '/icons/line/glosnik.png',
  kvm: '/icons/line/kvm.png',
  ergonomia: '/icons/line/ergonomia.png',
  daisy: '/icons/line/daisy.png',
  oko: '/icons/line/oko.png',
  // serwery
  rack: '/icons/line/rack.png',
  raid: '/icons/line/raid.png',
  dyski: '/icons/line/dyski.png',
  hotswap: '/icons/line/hotswap.png',
  zasilacze: '/icons/line/zasilacze.png',
  zdalne: '/icons/line/zdalne.png',
  rozbudowa: '/icons/line/rozbudowa.png',
  wsparcie5: '/icons/line/wsparcie5.png',
  // druk mobilny
  rolka: '/icons/line/rolka.png',
  etykieta: '/icons/line/etykieta.png',
  termotransfer: '/icons/line/termotransfer.png',
  archiwum: '/icons/line/archiwum.png',
  rfid: '/icons/line/rfid.png',
  bluetooth: '/icons/line/bluetooth.png',
  // urządzenia fiskalne i wdrożenie
  formularz: '/icons/em45/line/formularz.png',
  kurier: '/icons/em45/line/kurier.png',
  zamowienie: '/icons/line/zamowienie.png',
  fiskalizacja: '/icons/line/fiskalizacja.png',
  szkolenie: '/icons/line/szkolenie.png',
  integracja: '/icons/line/integracja.png',
  kalendarz: '/icons/line/kalendarz.png',
  karta: '/icons/line/karta.png',
  chmura: '/icons/line/chmura.png',
  paragon: '/icons/line/paragon.png',
  // akcesoria komputerowe
  torba: '/icons/line/torba.png',
  mysz: '/icons/line/mysz.png',
  podkladka: '/icons/line/podkladka.png',
  klodka: '/icons/line/klodka.png',
  aplikacje: '/icons/line/aplikacje.png',
  gniazdo: '/icons/line/gniazdo.png',
  napiecie: '/icons/line/napiecie.png',
  klucz: '/icons/line/klucz.png',
  podnozek: '/icons/line/podnozek.png',
  kat: '/icons/line/kat.png',
  antyposlizg: '/icons/line/antyposlizg.png',
  nadgarstek: '/icons/line/nadgarstek.png',
  wyscielenie: '/icons/line/wyscielenie.png',
  dokumenty: '/icons/line/dokumenty.png',
  odbiornik: '/icons/line/odbiornik.png',
  moc: '/icons/line/moc.png',
  transfer: '/icons/line/transfer.png',
  dyskzew: '/icons/line/dyskzew.png',
  urzadzenia: '/icons/line/urzadzenia.png',
  coldstart: '/icons/line/coldstart.png',
  biurko: '/icons/line/biurko.png',
  pojemnosc: '/icons/line/pojemnosc.png',
  precyzja: '/icons/line/precyzja.png',
  klawiszskrotu: '/icons/line/klawiszskrotu.png',
  // serwis
  diagnoza: '/icons/line/diagnoza.png',
  telefon: '/icons/line/telefon.png',
  zegar: '/icons/line/zegar.png',
  wycena: '/icons/line/wycena.png',
  ostrzezenie: '/icons/line/ostrzezenie.png',
  awaria: '/icons/line/awaria.png',
  // las
  drzewo: '/icons/line/drzewo.png',
  las: '/icons/line/las.png',
  lokalizacja: '/icons/line/lokalizacja.png',
  wspolpraca: '/icons/line/wspolpraca.png',
  // interfejs — nawigacja i sterowanie
  chevronPrawo: '/icons/line/chevronPrawo.png',
  chevronLewo: '/icons/line/chevronLewo.png',
  chevronGora: '/icons/line/chevronGora.png',
  chevronDol: '/icons/line/chevronDol.png',
  strzalka: '/icons/line/strzalka.png',
  strzalkaUkos: '/icons/line/strzalkaUkos.png',
  lupa: '/icons/line/lupa.png',
  menu: '/icons/line/menu.png',
  filtr: '/icons/line/filtr.png',
  lista: '/icons/line/lista.png',
  uzytkownik: '/icons/line/uzytkownik.png',
  kosz: '/icons/line/kosz.png',
  wyslij: '/icons/line/wyslij.png',
  podglad: '/icons/line/podglad.png',
  czat: '/icons/line/czat.png',
  budynek: '/icons/line/budynek.png',
  // kategorie sprzętu
  monitor: '/icons/line/monitor.png',
  drukarka: '/icons/line/drukarka.png',
  laptop: '/icons/line/laptop.png',
  tablet: '/icons/line/tablet.png',
  smartfon: '/icons/line/smartfon.png',
  rejestrator: '/icons/line/rejestrator.png',
  produkt: '/icons/line/produkt.png',
  serwer: '/icons/line/serwer.png',
  // interfejs
  zamknij: '/icons/line/zamknij.png',
  ptaszek: '/icons/line/ptaszek.png',
  info: '/icons/line/info.png',
  koperta: '/icons/line/koperta.png',
  // panel klienta
  pobierz: '/icons/line/pobierz.png',
  wyloguj: '/icons/line/wyloguj.png',
  edytuj: '/icons/line/edytuj.png',
  zapisz: '/icons/line/zapisz.png',
  instrukcja: '/icons/line/instrukcja.png',
  umowa: '/icons/line/umowa.png',
  // obsługa
  tarcza: '/icons/em45/line/tarcza.png',
  wsparcie: '/icons/line/wsparcie.png',
  onsite: '/icons/line/onsite.png',
  naprawa: '/icons/em45/line/naprawa.png',
  paczka: '/icons/em45/line/paczka.png',
  ekran: '/icons/line/jasnosc.png',
}

/** Ta sama ikona w wersji na ciemne tło: przezroczyste tło, biała kreska. */
export const naCiemnym = (src: string) => src.replace('/icons/', '/icons/white/')
